export const loginCopy = {
  brandMark: "PC",
  brandName: "ZAFU PC HOSPITAL",
  eyebrow: "Member Access",
  title: "成员登录",
  lead: "登录电脑医院综合服务平台，继续处理维修记录与成员事务。",
  qqLabel: "QQ 号",
  qqPlaceholder: "请输入已绑定的 QQ 号",
  passwordLabel: "密码",
  passwordPlaceholder: "请输入密码",
  showPassword: "显示密码",
  hidePassword: "隐藏密码",
  submit: "登录",
  submitting: "登录中",
  failed: "登录失败",
  registerPrompt: "尚未加入成员系统？",
  registerAction: "使用邀请码注册",
  backHome: "返回首页",
} as const;
